### ISSUE TITLE
Add path exclusion flag

### ISSUE THREAD

**Issue by jaredscheib** [s-yadav/relative-to-alias#2]
Awesome tool -- super helpful. Thanks for publishing it!

I'd like  to apply these aliases to an entire project folder, but can't because I need to be able to exclude `node_modules` and possibly other arbitrary directories. So I'm having to codemod the specific directions manually. It'd be great to have some kind of exclusion flag like `--exclude` or `--not-path`, to do one or more exclusions.

**Comment by s-yadav** [comment]
Yes, --exclude seems a good addition. Will work on that.

**Comment by s-yadav** [comment]
Added an ignore option to exclude folders. Available in v1.1.0
https://github.com/s-yadav/relative-to-alias#ignoring-folders

Let me know if you find any issue related to this.
